import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Nav } from "@/components/custom/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${inter.className} flex`}>
        <SidebarProvider>
        <Nav />
          <SidebarTrigger />
          <div className="flex-1">{children}</div>
    </SidebarProvider>
        </body>
      </html>
  );
}
